name: fluttr_protorecorder
description: A new flutter project.
version: 0.2.0

dependencies:
  flutter:
    sdk: flutter
  speech_recognition: ^0.2.0+1

flutter:

  uses-material-design: true

  assets:
    - assets/sytody.png